kind: pipeline
name: default

steps:
  # linting
  - name: linting the code
    image: golang
    commands:
      - go get -u golang.org/x/lint/golint
      - golint .
  # attempt to statically compile
  - name: attempt to compile
    image: golang
    commands:
      - go build
  # run tests for not hotdog
  - name: run unit tests
    image: golang
    commands:
      - go build
      - go test
    environment:
      AWS_ACCESS_KEY_ID:
        from: access_key_test
      AWS_SECRET_ACCESS_KEY:
        from: access_key_test
  # build production container
  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from: access_key_push
      secret_key:
        from: secret_key_push
      repo: nothotdog
      registry: 661723793673.dkr.ecr.us-west-2.amazonaws.com
      region: us-west-2
      