version: 0.2

phases:
  pre_build:
    commands:
    - echo logging into ECR
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
    - echo build started
    - docker build -t $IMAGE_REPO_NAME .
    - docker tag $IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_ID
  post_build:
    commands:
      - echo pushing docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_ID
      - aws ssm put-parameter --name not-hotdog-latest-image-id --value $CODEBUILD_BUILD_ID --type String