apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-hotdog
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hotdog
  template:
    metadata:
      labels:
        app: hotdog
    spec:
      containers:
        - image: public.ecr.aws/m6h8t0n2/not-hotdog:9e8a51a15e12632399201d4d185251a8ef900e46
          name: not-hotdog
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 2000m 
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-not-hotdog
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials-not-hotdog
                  key: AWS_SECRET_ACCESS_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 6443
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 6443
            periodSeconds: 5
          