apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nothotdog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: not-hotdog
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70