apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nothotdog-vsvc
spec:
  gateways:
  - nothotdog-ingress
  hosts:
    - not-hotdog.matthew-cloud.com
  http:
  - name: not-hotdog
    match:
      - uri:
          prefix: /
    route:
    - destination:
        host: nothotdog-svc
        port:
          number: 6443
      weight: 100

